# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget publish

on:
  workflow_dispatch:
    inputs:
      PackageVersion:
        description: 'Nuget package version.'
        required: true
        default: '1.0.0'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
        versionSpec: '6.0.x'
    - name: Determine Version
      id: version_step # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v3.1.1
    - name: Pack
      run: dotnet pack -o Artifacts /p:PackageVersion=${{ steps.version_step.outputs.fullSemVer }}
    - name: Push Nuget
      run: nuget push $GITHUB_WORKSPACE/Artifacts/AtToftegaard.Templates.${{ steps.version_step.outputs.fullSemVer }}.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_APIKEY }}
