name: Publish to Nuget

on:
  workflow_dispatch:
    inputs:
      PackageVersion:
        description: 'Nuget package version. This will be passed as next-version to gitversion. Leave empty to use the generated version.'
        required: false
        default: ''
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
        versionSpec: '6.0.x'
    - name: Determine Version
      id: version_step
      uses: gittools/actions/gitversion/execute@v3.1.1
      with:
        overrideConfig: |
          ${{ (github.event.inputs.PackageVersion != '')) { 'next-version='${{ github.event.inputs.PackageVersion }}'' }} 
        useConfigFile: true
    - name: Pack
      run: dotnet pack -o Artifacts /p:PackageVersion=${{ steps.version_step.outputs.fullSemVer }}
    - name: Push Nuget
      run: nuget push $GITHUB_WORKSPACE/Artifacts/AtToftegaard.Templates.${{ steps.version_step.outputs.fullSemVer }}.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_APIKEY }}
